[package]
name = "ferus"
version = "0.1.0"
authors = ["Alice McKean <mckeank@reed.edu>", "Henry Blanchette <blancheh@reed.edu>" ]
edition = "2018"

[dependencies]
combine = { git = "https://github.com/Marwes/combine" }
rustyline = "5.0.2"